# Generated by Django 6.0.6 on 2026-06-28 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question', models.CharField(choices=[('pet', 'Quel est le nom de votre premier animal de compagnie ?'), ('city', 'Quel est le nom de votre ville natale ?'), ('mother', 'Quel est le nom de jeune fille de votre mere ?'), ('movie', 'Quel est votre film prefere ?'), ('friend', 'Quel est le nom de votre meilleur ami d enfance ?'), ('school', 'Quelle est votre matiere preferee a l ecole ?')], max_length=20)),
                ('security_answer', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
