# Generated by Django 6.0.6 on 2026-06-23 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('realisateur', models.CharField(blank=True, max_length=255)),
                ('resume', models.TextField(blank=True)),
                ('annee_sortie', models.IntegerField(blank=True, null=True)),
                ('duree', models.IntegerField(blank=True, help_text='Durée en minutes', null=True)),
                ('statut', models.CharField(choices=[('a_voir', 'À voir'), ('vu', 'Vu'), ('favori', 'Favori')], default='a_voir', max_length=10)),
                ('poster_url', models.URLField(blank=True, max_length=500)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(related_name='movies', to='catalogue.genre')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
